[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de encabezados para API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Soporte para pnpm
[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/google-auth-callback"
  to = "https://whatsapp-bot-if6z.onrender.com/google-auth-callback"
  status = 200
  force = true 