// Blog data shared for blog and category pages
export const categories = [
  { name: "Inteligencia Artificial", slug: "inteligencia-artificial", count: 8 },
  { name: "Ventas", slug: "ventas", count: 12 },
  { name: "WhatsApp Business", slug: "whatsapp-business", count: 6 },
  { name: "Automatización", slug: "automatizacion", count: 9 },
  { name: "CRM", slug: "crm", count: 5 },
  { name: "Marketing Digital", slug: "marketing-digital", count: 7 },
];

const rawBlogPosts = [
  // Inteligencia Artificial
  {
    id: 1,
    title: "Cómo la IA está revolucionando las ventas por WhatsApp",
    excerpt: "Descubre cómo los agentes de inteligencia artificial están transformando la manera en que las empresas venden a través de WhatsApp y por qué es el momento perfecto para implementar esta tecnología en tu negocio.",
    date: "15 de mayo de 2023",
    readTime: "8 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=50&width=50",
    image: "/placeholder.svg?height=400&width=800",
    slug: "como-ia-revoluciona-ventas-whatsapp",
    category: "Inteligencia Artificial",
  },
  {
    id: 2,
    title: "El futuro de la atención al cliente: Humanos y bots trabajando juntos",
    excerpt: "Analizamos cómo la combinación de agentes humanos y virtuales crea la experiencia de cliente perfecta y potencia las ventas.",
    date: "10 de agosto de 2023",
    readTime: "7 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "futuro-atencion-cliente-humanos-bots",
    category: "Inteligencia Artificial",
  },
  {
    id: 3,
    title: "Machine Learning aplicado a la calificación de leads",
    excerpt: "Cómo los algoritmos de aprendizaje automático pueden identificar a los prospectos con mayor potencial de compra y optimizar tu embudo de ventas.",
    date: "25 de septiembre de 2023",
    readTime: "9 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "machine-learning-calificacion-leads",
    category: "Inteligencia Artificial",
  },
  {
    id: 4,
    title: "Personalización a escala: El poder del NLP en ventas",
    excerpt: "Descubre cómo el procesamiento del lenguaje natural permite crear conversaciones personalizadas con miles de clientes simultáneamente.",
    date: "3 de octubre de 2023",
    readTime: "6 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "personalizacion-escala-nlp-ventas",
    category: "Inteligencia Artificial",
  },
  {
    id: 5,
    title: "La revolución de los LLMs en el comercio electrónico",
    excerpt: "Cómo los modelos de lenguaje de gran escala están transformando la experiencia de compra online y aumentando las conversiones.",
    date: "17 de noviembre de 2023",
    readTime: "8 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "revolucion-llms-comercio-electronico",
    category: "Inteligencia Artificial",
  },
  {
    id: 29,
    title: "IA generativa en ventas: Casos de uso reales en 2024",
    excerpt: "Descubre cómo la inteligencia artificial generativa está revolucionando los procesos de ventas en empresas líderes.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "ia-generativa-ventas-casos-uso-2024",
    category: "Inteligencia Artificial",
  },
  {
    id: 30,
    title: "Chatbots avanzados: Cómo elegir el mejor para tu negocio",
    excerpt: "Guía para seleccionar el chatbot de IA más adecuado según el sector y el tamaño de tu empresa.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "chatbots-avanzados-como-elegir-mejor-negocio",
    category: "Inteligencia Artificial",
  },
  {
    id: 31,
    title: "Ética y transparencia en IA: Lo que toda empresa debe saber",
    excerpt: "Aspectos éticos y normativos clave para implementar IA de forma responsable en tu organización.",
    date: "21 de junio de 2024",
    readTime: "6 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "etica-transparencia-ia-empresas",
    category: "Inteligencia Artificial",
  },
  // Ventas
  {
    id: 6,
    title: "Casos de éxito: Empresas que aumentaron sus ventas un 40% con BEXOR",
    excerpt: "Conoce las historias reales de empresas que transformaron su proceso de ventas implementando nuestro agente AI.",
    date: "22 de julio de 2023",
    readTime: "10 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "casos-exito-empresas-aumentaron-ventas-bexor",
    category: "Ventas",
  },
  {
    id: 7,
    title: "7 técnicas de cierre de ventas que todo bot debería implementar",
    excerpt: "Estrategias probadas para incrementar la tasa de conversión que puedes aplicar en tu agente AI de ventas.",
    date: "14 de agosto de 2023",
    readTime: "11 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "tecnicas-cierre-ventas-bot",
    category: "Ventas",
  },
  {
    id: 8,
    title: "Cómo manejar objeciones de ventas con inteligencia artificial",
    excerpt: "Guía definitiva para programar respuestas efectivas a las objeciones más comunes que presentan los clientes potenciales.",
    date: "29 de septiembre de 2023",
    readTime: "9 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "manejar-objeciones-ventas-inteligencia-artificial",
    category: "Ventas",
  },
  {
    id: 9,
    title: "El arte de la persuasión digital: Psicología aplicada a las ventas automatizadas",
    excerpt: "Principios psicológicos que puedes implementar en tus estrategias de venta digital para aumentar la efectividad.",
    date: "12 de octubre de 2023",
    readTime: "7 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "arte-persuasion-digital-psicologia-ventas",
    category: "Ventas",
  },
  {
    id: 32,
    title: "Ventas B2B en la era digital: Estrategias que funcionan en 2024",
    excerpt: "Las mejores prácticas y herramientas para potenciar tus ventas B2B con tecnología y datos.",
    date: "21 de junio de 2024",
    readTime: "9 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "ventas-b2b-estrategias-digitales-2024",
    category: "Ventas",
  },
  {
    id: 33,
    title: "Cómo crear un embudo de ventas automatizado con IA",
    excerpt: "Paso a paso para diseñar un embudo de ventas eficiente usando inteligencia artificial y automatización.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "embudo-ventas-automatizado-ia",
    category: "Ventas",
  },
  {
    id: 34,
    title: "Técnicas de cierre de ventas para ecommerce en 2024",
    excerpt: "Estrategias de cierre adaptadas al comercio electrónico y a los nuevos hábitos de compra online.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "tecnicas-cierre-ventas-ecommerce-2024",
    category: "Ventas",
  },
  {
    id: 35,
    title: "Storytelling en ventas: Cómo conectar emocionalmente con tus clientes",
    excerpt: "El arte de contar historias para persuadir y fidelizar en el proceso de ventas digital.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "storytelling-ventas-conexion-clientes",
    category: "Ventas",
  },
  {
    id: 36,
    title: "Ventas consultivas: El nuevo rol del vendedor digital",
    excerpt: "Cómo la venta consultiva y el análisis de datos están redefiniendo el perfil del vendedor moderno.",
    date: "21 de junio de 2024",
    readTime: "9 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "ventas-consultivas-vendedor-digital",
    category: "Ventas",
  },
  {
    id: 37,
    title: "Cómo medir el ROI de tus campañas de ventas digitales",
    excerpt: "Indicadores clave y herramientas para calcular el retorno de inversión en ventas online.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "medir-roi-campanas-ventas-digitales",
    category: "Ventas",
  },
  {
    id: 38,
    title: "Neuromarketing aplicado a ventas: Ciencia y práctica",
    excerpt: "Cómo los descubrimientos en neurociencia están influyendo en las técnicas de venta digital.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "neuromarketing-aplicado-ventas-ciencia-practica",
    category: "Ventas",
  },
  // WhatsApp Business
  {
    id: 10,
    title: "Cómo integrar WhatsApp Business API con tu CRM actual",
    excerpt: "Aprende a conectar la API de WhatsApp Business con tu sistema CRM para una gestión unificada de clientes y seguimiento efectivo de conversaciones.",
    date: "18 de octubre de 2023",
    readTime: "9 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "integrar-whatsapp-business-api-crm",
    category: "WhatsApp Business",
  },
  {
    id: 11,
    title: "Cumplimiento normativo en WhatsApp Business: Guía completa 2023",
    excerpt: "Todo lo que necesitas saber sobre las políticas de Meta, protección de datos y mejores prácticas para no infringir normas.",
    date: "5 de noviembre de 2023",
    readTime: "10 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "cumplimiento-normativo-whatsapp-business",
    category: "WhatsApp Business",
  },
  {
    id: 12,
    title: "Catálogos inteligentes en WhatsApp: Cómo implementarlos con IA",
    excerpt: "Guía paso a paso para crear catálogos dinámicos y personalizados que se adapten a las preferencias de cada cliente.",
    date: "21 de noviembre de 2023",
    readTime: "8 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "catalogos-inteligentes-whatsapp-ia",
    category: "WhatsApp Business",
  },
  {
    id: 39,
    title: "WhatsApp Business vs. Email: ¿Cuál es mejor para tu estrategia de ventas?",
    excerpt: "Comparativa de ventajas, tasas de apertura y conversión entre WhatsApp Business y el email marketing.",
    date: "21 de junio de 2024",
    readTime: "6 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "whatsapp-business-vs-email-estrategia-ventas",
    category: "WhatsApp Business",
  },
  {
    id: 40,
    title: "Automatización de respuestas en WhatsApp: Mejores prácticas 2024",
    excerpt: "Cómo configurar respuestas automáticas efectivas en WhatsApp Business para mejorar la atención al cliente.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-respuestas-whatsapp-business-2024",
    category: "WhatsApp Business",
  },
  // Automatización
  {
    id: 13,
    title: "5 estrategias para optimizar tu bot de ventas",
    excerpt: "Aprende las mejores prácticas para configurar tu agente AI y maximizar las conversiones en tu negocio.",
    date: "3 de junio de 2023",
    readTime: "6 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "5-estrategias-optimizar-bot-ventas",
    category: "Automatización",
  },
  {
    id: 14,
    title: "Guía completa para entrenar a tu bot de ventas",
    excerpt: "Todo lo que necesitas saber para personalizar y optimizar tu agente AI para tu nicho de mercado específico y aumentar su efectividad.",
    date: "5 de septiembre de 2023",
    readTime: "12 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "guia-completa-entrenar-bot-ventas",
    category: "Automatización",
  },
  {
    id: 15,
    title: "Automatización del seguimiento de leads: Aumenta tu tasa de conversión",
    excerpt: "Estrategias y técnicas para implementar un sistema de seguimiento automatizado que no deje escapar ninguna oportunidad de venta.",
    date: "19 de octubre de 2023",
    readTime: "9 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-seguimiento-leads",
    category: "Automatización",
  },
  {
    id: 16,
    title: "Flujos de trabajo automatizados: Del lead a la venta",
    excerpt: "Cómo diseñar procesos automáticos que guíen al cliente a través de todo el embudo de ventas sin intervención humana.",
    date: "7 de noviembre de 2023",
    readTime: "11 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "flujos-trabajo-automatizados-lead-venta",
    category: "Automatización",
  },
  {
    id: 41,
    title: "Automatización en ventas: Cómo escalar sin perder personalización",
    excerpt: "Estrategias para automatizar procesos de ventas manteniendo la experiencia personalizada del cliente.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-ventas-escalar-personalizacion",
    category: "Automatización",
  },
  {
    id: 42,
    title: "RPA en pymes: Automatización robótica de procesos al alcance de todos",
    excerpt: "Cómo las pequeñas empresas pueden aprovechar la RPA para optimizar tareas repetitivas y ahorrar costos.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "rpa-pymes-automatizacion-robotica-procesos",
    category: "Automatización",
  },
  {
    id: 43,
    title: "Automatización y analítica: Cómo medir el impacto real en tu negocio",
    excerpt: "Indicadores y métricas clave para evaluar el éxito de la automatización en tu empresa.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-analitica-medir-impacto-negocio",
    category: "Automatización",
  },
  {
    id: 44,
    title: "Automatización en atención al cliente: Casos de éxito 2024",
    excerpt: "Ejemplos reales de empresas que han transformado su servicio al cliente con automatización.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-atencion-cliente-casos-exito-2024",
    category: "Automatización",
  },
  {
    id: 45,
    title: "Automatización y sostenibilidad: Cómo reducir el impacto ambiental",
    excerpt: "Descubre cómo la automatización puede contribuir a la sostenibilidad y la eficiencia energética en tu empresa.",
    date: "21 de junio de 2024",
    readTime: "6 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-sostenibilidad-reducir-impacto-ambiental",
    category: "Automatización",
  },
  // CRM
  {
    id: 17,
    title: "CRM e IA: La combinación perfecta para aumentar ventas",
    excerpt: "Cómo integrar herramientas de inteligencia artificial en tu CRM actual para potenciar su efectividad y generar más ingresos.",
    date: "13 de septiembre de 2023",
    readTime: "8 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "crm-ia-combinacion-perfecta-ventas",
    category: "CRM",
  },
  {
    id: 18,
    title: "Análisis predictivo en CRM: Anticípate a las necesidades de tus clientes",
    excerpt: "Cómo utilizar datos históricos y algoritmos de predicción para identificar oportunidades de venta antes de que ocurran.",
    date: "27 de octubre de 2023",
    readTime: "10 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "analisis-predictivo-crm",
    category: "CRM",
  },
  {
    id: 19,
    title: "Integración de múltiples canales en tu CRM con BEXOR",
    excerpt: "Unifica WhatsApp, email, redes sociales y más en una sola plataforma para ofrecer una experiencia omnicanal perfecta.",
    date: "15 de noviembre de 2023",
    readTime: "7 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "integracion-multicanal-crm-bexor",
    category: "CRM",
  },
  {
    id: 46,
    title: "Integraciones CRM: Cómo conectar todas tus herramientas en 2024",
    excerpt: "Guía para integrar tu CRM con otras plataformas y maximizar la eficiencia de tu equipo.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "integraciones-crm-conectar-herramientas-2024",
    category: "CRM",
  },
  // Marketing Digital
  {
    id: 20,
    title: "WhatsApp como canal de marketing: Estrategias que funcionan",
    excerpt: "Cómo convertir WhatsApp en una herramienta efectiva de marketing digital que respete la privacidad y genere resultados.",
    date: "8 de septiembre de 2023",
    readTime: "9 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "whatsapp-canal-marketing-estrategias",
    category: "Marketing Digital",
  },
  {
    id: 21,
    title: "Optimización de campañas publicitarias con datos de conversaciones",
    excerpt: "Aprovecha la información recopilada por tu bot de ventas para mejorar la segmentación y efectividad de tus campañas.",
    date: "29 de octubre de 2023",
    readTime: "8 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "optimizacion-campanas-datos-conversaciones",
    category: "Marketing Digital",
  },
  {
    id: 22,
    title: "Marketing conversacional: El futuro de la interacción con clientes",
    excerpt: "Cómo implementar estrategias conversacionales que humanicen tu marca y generen conexiones más profundas con tu audiencia.",
    date: "11 de noviembre de 2023",
    readTime: "7 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "marketing-conversacional-futuro-interaccion",
    category: "Marketing Digital",
  },
  {
    id: 23,
    title: "Estrategias de SEO para 2024: Cómo adaptarse a los nuevos algoritmos",
    excerpt: "Una guía completa de las mejores prácticas SEO para el próximo año, incluyendo optimización para búsqueda por voz y inteligencia artificial.",
    date: "10 de diciembre de 2023",
    readTime: "12 min de lectura",
    author: "BEXOR AI",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "estrategias-seo-2024-algoritmos",
    category: "Marketing Digital",
  },
  {
    id: 25,
    title: "WhatsApp Business para ecommerce: Estrategias que aumentan las ventas",
    excerpt: "Aprende cómo las tiendas online están usando WhatsApp Business para incrementar conversiones y fidelizar clientes en 2024.",
    date: "20 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "whatsapp-business-ecommerce-estrategias-ventas",
    category: "WhatsApp Business",
  },
  {
    id: 26,
    title: "Automatización de marketing: Herramientas y flujos que dominan 2024",
    excerpt: "Conoce las mejores herramientas y flujos de automatización de marketing que están revolucionando la captación y retención de clientes este año.",
    date: "20 de junio de 2024",
    readTime: "9 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "automatizacion-marketing-herramientas-flujos-2024",
    category: "Automatización",
  },
  {
    id: 27,
    title: "SEO local en 2024: Cómo dominar las búsquedas 'cerca de mí'",
    excerpt: "Descubre las mejores prácticas y estrategias para posicionar tu negocio en las búsquedas locales y captar clientes en tu zona.",
    date: "20 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "seo-local-2024-busquedas-cerca-de-mi",
    category: "Marketing Digital",
  },
  {
    id: 28,
    title: "Psicología de ventas digital: Trucos y técnicas que realmente funcionan",
    excerpt: "Explora los principios psicológicos más efectivos para aumentar tus ventas online y mejorar la conversión en entornos digitales.",
    date: "20 de junio de 2024",
    readTime: "10 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "psicologia-ventas-digital-trucos-tecnicas",
    category: "Ventas",
  },
  {
    id: 47,
    title: "Tendencias de video marketing para 2024: Plataformas y formatos ganadores",
    excerpt: "Las mejores prácticas y plataformas para destacar con video marketing este año.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "tendencias-video-marketing-2024",
    category: "Marketing Digital",
  },
  {
    id: 48,
    title: "Publicidad programática: Cómo funciona y por qué es clave en 2024",
    excerpt: "Explicación sencilla de la publicidad programática y su impacto en el marketing digital actual.",
    date: "21 de junio de 2024",
    readTime: "8 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "publicidad-programatica-como-funciona-2024",
    category: "Marketing Digital",
  },
  {
    id: 49,
    title: "Google Analytics 4: Métricas imprescindibles para tu estrategia digital",
    excerpt: "Aprende a sacar el máximo partido a GA4 con las métricas más relevantes para tu negocio.",
    date: "21 de junio de 2024",
    readTime: "7 min de lectura",
    author: "BEXOR IA",
    authorImage: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=200&width=400",
    slug: "google-analytics-4-metricas-estrategia-digital",
    category: "Marketing Digital",
  },
]; 

// Assign cover images to posts by cycling through the 8 public images
const coverImages = [
  "/Diseño sin título (5)/1.png",
  "/Diseño sin título (5)/2.png",
  "/Diseño sin título (5)/3.png",
  "/Diseño sin título (5)/4.png",
  "/Diseño sin título (5)/5.png",
  "/Diseño sin título (5)/6.png",
  "/Diseño sin título (5)/7.png",
  "/Diseño sin título (5)/8.png",
];

export const blogPosts = rawBlogPosts.map((post, index) => {
  // Override image for featured WhatsApp IA post with proper URI encoding
  if (post.slug === "como-ia-revoluciona-ventas-whatsapp") {
    return {
      ...post,
      image: encodeURI("/Diseño sin título (5)/Diseño sin título (17).png"),
    };
  }
  return {
    ...post,
    image: coverImages[index % coverImages.length],
  };
}); 